# This file was generated by GoReleaser. DO NOT EDIT.
cask "tenuvault" do
  version "1.7.1"

  on_macos do
    on_arm do
      sha256 "e3d0a8bbd1af79a3fc4dbe6b375ad17ffd7ab1ebf2a5e540efd58ea5e9f3be75"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d0ea2e33543fdf5b93085a81e420adc0cb38aa6ac09f32c75de9cc44a4bc410"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "285bf5a941529dd26a4eabe3ea389685586ad1a1c7845c5967944618faa2167f"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tenuvault"
  desc "Terminal UI for backing up and restoring Microsoft Intune via Microsoft Graph"
  homepage "https://github.com/ugurkocde/TenuVault-TUI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tenuvault"

  # No zap stanza required

end
