# This file was generated by GoReleaser. DO NOT EDIT.
cask "tenuvault" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "4c99089aff1f6fddcd9b9de2649b017bb0e5cf2486a7d431a50bfc8470ba3808"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5683e04afac5dfdb90894b6d62e40542ed73f70307588d964b37ac3e2f2eefd0"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b561d6eec083ab7dba345334e45ee6d48b2e7e3075889fd6d793796e52891f6f"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "03211cf827814b2500ee9125877a4af4fbcb38148889fd33becd078ef6ea7c05"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tenuvault"
  desc "Terminal UI for backing up and restoring Microsoft Intune via Microsoft Graph"
  homepage "https://github.com/ugurkocde/TenuVault-TUI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tenuvault"

  # No zap stanza required

end
