# This file was generated by GoReleaser. DO NOT EDIT.
cask "tenuvault" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "33b43878880b4883ba3787ab5bd68bdcc459a20f81a841c47e935c9810f13e66"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6208e6885adaf555c4e8d964f279f5995a6127dd2d993b69dfb6101fff0ad331"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "24f0f3add7e6efb281b24855771547806d2932d2f15fad41f9006409116fbd38"
      url "https://github.com/ugurkocde/TenuVault-TUI/releases/download/v#{version}/tenuvault_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tenuvault"
  desc "Terminal UI for backing up and restoring Microsoft Intune via Microsoft Graph"
  homepage "https://github.com/ugurkocde/TenuVault-TUI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tenuvault"

  # No zap stanza required

end
